# Generated by Django 5.2.8 on 2025-12-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_itemcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cover_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='activity',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
